import { requireVerifiedUser } from '@/lib/auth/session';
import { pageClient } from '@/lib/supabase/pageClient';
import { getCostControl,getEstimateDraftControls,type CostControlWedding,type CostControlItem } from '@/lib/data/cost-control';
import { HostNav } from '../HostNav';
import { addCostItem,beginEstimateReview,decideCommitment,decideEstimate,initializeCostControl,proposeCommitment,recordInvoice,recordPayment,saveEstimate,submitEstimate,verifyInvoice,voidPayment } from './actions';

export const dynamic='force-dynamic';
const money=(n:number,c:string)=>new Intl.NumberFormat(c==='INR'?'en-IN':'en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(n);
const Hidden=({w,item}:{w:string;item?:string})=><><input type="hidden" name="weddingId" value={w}/>{item?<input type="hidden" name="itemId" value={item}/>:null}</>;

function EstimateForm({w,item,estimate}:{w:string;item:string;estimate?:CostControlItem['estimates'][number]}){return <form action={saveEstimate} className="sg-formrow"><Hidden w={w} item={item}/>{estimate?<input type="hidden" name="estimateId" value={estimate.id}/>:null}
  <label className="sg-field"><span className="sg-label">Estimate *</span><input className="sg-input" type="number" min="0" step="0.01" name="subtotal" required defaultValue={estimate?.subtotal}/></label>
  <label className="sg-field"><span className="sg-label">Tax %</span><input className="sg-input" type="number" min="0" max="100" step="0.01" name="taxRate" defaultValue={estimate?.taxRate??0}/></label>
  <label className="sg-field"><span className="sg-label">Currency</span><select className="sg-select" name="currency" defaultValue={estimate?.currency??'INR'}><option>INR</option><option>USD</option></select></label>
  <label className="sg-field"><span className="sg-label">Included scope</span><input className="sg-input" name="scopeIncluded" defaultValue={estimate?.scopeIncluded??''}/></label>
  <label className="sg-field"><span className="sg-label">Excluded scope</span><input className="sg-input" name="scopeExcluded" defaultValue={estimate?.scopeExcluded??''}/></label>
  <label className="sg-field"><span className="sg-label">Decision due</span><input className="sg-input" type="datetime-local" name="decisionDue" defaultValue={estimate?.decisionDue?.slice(0,16)}/></label>
  <label className="sg-field"><span className="sg-label">Remarks</span><input className="sg-input" name="remarks" defaultValue={estimate?.remarks??''}/></label>
  <button className="sg-btn sg-btn--primary" type="submit">Save draft</button></form>;}

function DecisionForm({w,id,kind}:{w:string;id:string;kind:'estimate'|'commitment'}){
  const action=kind==='estimate'?decideEstimate:decideCommitment;
  return <form action={action} className="sg-formrow"><Hidden w={w}/><input type="hidden" name={kind==='estimate'?'estimateId':'commitmentId'} value={id}/>
    <select className="sg-select" name="decision"><option value="approved">Approve</option>{kind==='estimate'?<option value="revision_required">Request revision</option>:null}<option value="rejected">Reject</option></select>
    <input className="sg-input" name="reason" required placeholder="Decision reason"/><button className="sg-btn sg-btn--primary">Record decision</button></form>;
}

function ItemCard({w,item}:{w:CostControlWedding;item:CostControlItem}){const approved=item.estimates.find((e)=>e.state==='approved'); const approvedCommitments=item.commitments.filter((c)=>c.state==='approved'); const draftControls=getEstimateDraftControls(item.estimates);
  return <section className="sg-section"><h2>{item.title} <span className="sg-badge is-off">{item.state}</span></h2><p className="sg-muted">{item.centreName}{item.description?` · ${item.description}`:''}</p>
    <h3>Estimate versions</h3>{item.estimates.length?<div className="sg-tablewrap"><table className="sg-table"><thead><tr><th>Version</th><th>Status</th><th>Total</th><th>Action</th></tr></thead><tbody>{item.estimates.map((e)=><tr key={e.id}><td>v{e.version}</td><td>{e.state.replace('_',' ')}</td><td>{money(e.total,e.currency)}</td><td>
      {e.state==='draft'&&e.canEditDraft?<><details><summary>Edit draft</summary><EstimateForm w={w.weddingId} item={item.id} estimate={e}/></details><form action={submitEstimate}><Hidden w={w.weddingId}/><input type="hidden" name="estimateId" value={e.id}/><button className="sg-btn sg-btn--sm">Submit</button></form></>:null}
      {e.state==='submitted'&&w.isCostApprover?<form action={beginEstimateReview}><Hidden w={w.weddingId}/><input type="hidden" name="estimateId" value={e.id}/><button className="sg-btn sg-btn--sm">Start review</button></form>:null}
      {e.state==='under_review'&&w.isCostApprover?<DecisionForm w={w.weddingId} id={e.id} kind="estimate"/>:null}
    </td></tr>)}</tbody></table></div>:<p className="sg-muted">No estimate yet.</p>}
    {draftControls.showCreateDraft?<details><summary>{draftControls.createDraftLabel}</summary><EstimateForm w={w.weddingId} item={item.id}/></details>:null}
    {approved?<details><summary>Propose official commitment</summary><form action={proposeCommitment} className="sg-formrow"><Hidden w={w.weddingId} item={item.id}/><input type="hidden" name="estimateId" value={approved.id}/><input className="sg-input" name="reference" placeholder="Quote / contract reference"/><input className="sg-input" type="date" name="commitmentDate"/><button className="sg-btn sg-btn--primary">Propose</button></form></details>:null}
    {item.commitments.length?<><h3>Commitments</h3>{item.commitments.map((c)=><div key={c.id} className="sg-callout"><strong>{money(c.total,c.currency)}</strong> · {c.state}{c.reference?` · ${c.reference}`:''}{c.state==='proposed'&&w.isCostApprover?<DecisionForm w={w.weddingId} id={c.id} kind="commitment"/>:null}</div>)}</>:null}
    <details><summary>Official records (optional)</summary><p className="sg-muted">Invoices and payment status are optional. Estimate and approval tracking remains the default journey.</p>{approvedCommitments.map((c)=><details key={c.id}><summary>Record invoice against {c.reference??'approved commitment'}</summary><form action={recordInvoice} className="sg-formrow"><Hidden w={w.weddingId} item={item.id}/><input type="hidden" name="commitmentId" value={c.id}/><input className="sg-input" name="reference" required placeholder="Invoice reference"/><input className="sg-input" type="number" min="0" step="0.01" name="subtotal" required placeholder="Subtotal"/><input className="sg-input" type="number" min="0" max="100" step="0.01" name="taxRate" defaultValue="0"/><select className="sg-select" name="currency" defaultValue={c.currency}><option>INR</option><option>USD</option></select><input className="sg-input" type="date" name="dueDate"/><button className="sg-btn sg-btn--primary">Record invoice</button></form></details>)}
    {item.invoices.length?<><h3>Official invoices</h3>{item.invoices.map((i)=><div className="sg-callout" key={i.id}><strong>{i.reference}</strong> · {money(i.total,i.currency)} · {i.state.replace('_',' ')}
      {i.state==='received'&&w.isCostApprover?<form action={verifyInvoice} className="sg-formrow"><Hidden w={w.weddingId}/><input type="hidden" name="invoiceId" value={i.id}/><input className="sg-input" name="reason" required placeholder="Verification reason"/><button className="sg-btn sg-btn--primary">Verify</button></form>:null}
      {['verified','part_paid'].includes(i.state)&&w.isCostApprover?<form action={recordPayment} className="sg-formrow"><Hidden w={w.weddingId}/><input type="hidden" name="invoiceId" value={i.id}/><input className="sg-input" type="number" min="0.01" step="0.01" name="amount" required placeholder="Official paid amount"/><input className="sg-input" type="date" name="paidOn" required/><select className="sg-select" name="method"><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="cash">Cash</option><option value="cheque">Cheque</option><option value="other">Other</option></select><input className="sg-input" name="reference" placeholder="Official reference"/><button className="sg-btn sg-btn--primary">Record payment status</button></form>:null}
      {i.payments.map((p)=><div key={p.id} className="sg-muted">{p.voided?'Voided: ':''}{money(p.amount,i.currency)} · {p.paidOn} · {p.reference??p.method}{!p.voided&&w.isCostApprover?<form action={voidPayment} style={{display:'inline-flex',gap:8,marginLeft:8}}><Hidden w={w.weddingId}/><input type="hidden" name="paymentId" value={p.id}/><input className="sg-input" name="reason" required placeholder="Void reason"/><button className="sg-btn sg-btn--danger sg-btn--sm">Void</button></form>:null}</div>)}
    </div>)}</>:null}</details>
  </section>;
}

function WeddingCostControl({w}:{w:CostControlWedding}){return <div><div className="sg-pagehead"><h1>Cost Control · {w.title}</h1><p>Start with estimates and approvals. Official invoices and payment status are optional. Do not enter bank details, family contributions, funding sources or private settlements.</p></div>
  {w.summary.length?<section className="sg-section"><h2>Official position</h2><div className="sg-statgrid">{w.summary.map((s)=><div className="sg-stat" key={s.currency}><span className="sg-stat__label">{s.currency}</span><strong>Approved {money(s.approved,s.currency)}</strong><span>Committed {money(s.committed,s.currency)} · Invoiced {money(s.invoiced,s.currency)} · Recorded paid {money(s.paid,s.currency)}</span></div>)}</div></section>:null}
  {!w.centres.length?<section className="sg-section"><h2>Start Cost Control</h2><p>Load the standard Indian-wedding cost headings. This creates no budget ceiling or family funding record.</p><form action={initializeCostControl}><Hidden w={w.weddingId}/><button className="sg-btn sg-btn--primary">Load standard headings</button></form></section>:<section className="sg-section"><h2>Add a cost item</h2><form action={addCostItem} className="sg-formrow"><Hidden w={w.weddingId}/><select className="sg-select" name="centreId">{w.centres.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="sg-input" name="title" required placeholder="Official cost item"/><input className="sg-input" name="description" placeholder="Scope note"/><input className="sg-input" type="date" name="decisionDue"/><button className="sg-btn sg-btn--primary">Add item</button></form></section>}
  {w.items.map((item)=><ItemCard key={item.id} w={w} item={item}/>)}</div>;}

export default async function CostControlPage({searchParams}:{searchParams:Promise<{ok?:string;err?:string}>}){await requireVerifiedUser('/host/cost-control');const sp=await searchParams;let weddings:CostControlWedding[]=[];let failed=false;try{weddings=await getCostControl(await pageClient());}catch(error){console.error('[sangam cost-control] load',error);failed=true;}
  return <main className="sg-host"><div className="sg-host-shell"><HostNav current="cost-control"/>{sp.ok?<div className="sg-banner is-ok">Saved.</div>:sp.err||failed?<div className="sg-banner is-err">We couldn’t complete that Cost Control action. Check the details and try again.</div>:null}{weddings.length?weddings.map((w)=><WeddingCostControl key={w.weddingId} w={w}/>):<div className="sg-pagehead"><h1>Cost Control</h1><p>Your account is not appointed as an event manager or cost approver for a wedding.</p></div>}</div></main>;}
