import {requireVerifiedUser} from '@/lib/auth/session';import {pageClient} from '@/lib/supabase/pageClient';import {HostNav} from '../../HostNav';
import {configureRoomSheet,refreshRoomSheet,reviewRoomSheetChanges,commitReviewedRoomSheetChanges} from './actions';
export const dynamic='force-dynamic';
export default async function RoomSheetPage({searchParams}:{searchParams:Promise<{wedding?:string;ok?:string;err?:string}>}){await requireVerifiedUser('/host/stay/sheet');const sp=await searchParams;const db=await pageClient();const app=db.schema('app');
 const weddings=await app.from('operator_role').select('wedding_id').eq('role','wedding_owner');const wedding=sp.wedding??weddings.data?.[0]?.wedding_id??'';
 const connection=wedding?await app.from('sheet_sync_connection').select('*').eq('wedding_id',wedding).maybeSingle():null;
 const run=wedding?await app.from('sheet_sync_run').select('*').eq('wedding_id',wedding).order('created_at',{ascending:false}).limit(1).maybeSingle():null;
 const changes=run?.data?await app.from('sheet_sync_change').select('*').eq('run_id',run.data.id).order('created_at'):null;
 return <main className="sg-host"><div className="sg-host-shell"><HostNav current="stay"/><div className="sg-pagehead"><h1>Room Sheet synchronization</h1><p>Sangam remains authoritative. Sheet edits are reviewed here and change nothing until you commit accepted rows.</p></div>
 {sp.ok?<div className="sg-banner is-ok">Completed: {sp.ok}.</div>:null}{sp.err?<div className="sg-banner is-err">The operation could not be completed ({sp.err}).</div>:null}
 {!wedding?<section className="sg-section"><p>No owner-managed wedding is available.</p></section>:!connection?.data?<section className="sg-section"><h2>Connect the pilot workbook</h2><form action={configureRoomSheet} className="sg-formrow"><input type="hidden" name="weddingId" value={wedding}/><input className="sg-input" name="spreadsheetId" required defaultValue={process.env.ROOM_SHEET_SPREADSHEET_ID??''}/><button className="sg-btn sg-btn--primary">Connect safely</button></form></section>:
 <><section className="sg-section"><h2>Controlled workflow</h2><p><strong>Workbook:</strong> {connection.data.spreadsheet_id}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><form action={refreshRoomSheet}><input type="hidden" name="weddingId" value={wedding}/><button className="sg-btn sg-btn--ghost">Refresh Sheet from Sangam</button></form><form action={reviewRoomSheetChanges}><input type="hidden" name="weddingId" value={wedding}/><button className="sg-btn sg-btn--primary">Review Sheet changes</button></form></div></section>
 {run?.data?<section className="sg-section"><h2>Latest review · {run.data.status}</h2>{changes?.data?.length?<form action={commitReviewedRoomSheetChanges}><input type="hidden" name="weddingId" value={wedding}/><input type="hidden" name="runId" value={run.data.id}/><div className="sg-tablewrap"><table className="sg-table"><thead><tr><th>Commit</th><th>Row</th><th>Result</th><th>Reason</th></tr></thead><tbody>{changes.data.map((c)=><tr key={c.id}><td>{c.validation_status==='accepted'?<input type="checkbox" name="changeId" value={c.id} defaultChecked/>:'—'}</td><td>{c.change_key}</td><td>{c.validation_status}</td><td>{c.validation_codes.join(', ')||'Ready'}</td></tr>)}</tbody></table></div>{changes.data.some((c)=>c.validation_status==='accepted')?<button className="sg-btn sg-btn--green" style={{marginTop:12}}>Commit selected accepted changes</button>:null}</form>:<p>No changed rows were detected.</p>}</section>:null}</>}</div></main>}
